todo/urls.py
from django.contrib import admin
from django.urls import path
from todo.views import list_view, delete_task, home_view, add_item, add_list, done_task

app_name = 'todo'

urlpatterns = [
    path('', home_view, name='home'),
    path('list/', list_view, name='list'),
    path('task-edit/<int:id>', list_view, name='edit'),
    path('task-delete/<int:id>', delete_task, name='delete'),
    path('task-add/<int:id>', add_item, name='add-item'),
    path('list-add/', add_list, name='add-list'),
    path('task-done/<int:id>', done_task, name='done'),
]

todoList/urls.py
from django.contrib import admin
from django.urls import include, path
from todoList.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('todo.urls', namespace='todo')),
    path('home/', home_view),
]

users/urls.py
from django.contrib import admin
from django.urls import include, path
from users.views import login_view, register_view, logout_view

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

todo/models.py
from django.db import models
from users.models import CustomUser


class TodoItem(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='id', blank=True)
    title = models.TextField(max_length=255, verbose_name='title')
    description = models.TextField(max_length=255, verbose_name='description')
    done = models.BooleanField(verbose_name='done', default=False)

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def __str__(self) -> str:
        return self.title


class TodoList(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='id', blank=True)
    title = models.TextField(max_length=255, verbose_name='title')
    description = models.TextField(max_length=255, verbose_name='description')

    class Meta:
        verbose_name = 'Todo List'
        verbose_name_plural = 'Todo Lists'

    def __str__(self) -> str:
        return self.title


class ListItems(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='id', blank=True)
    list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, to_field='id')
    item = models.ForeignKey(
        TodoItem, on_delete=models.CASCADE, to_field='id')

    class Meta:
        verbose_name = 'List Item'
        verbose_name_plural = 'List Items'
    
    def __str__(self) -> str:
        return f'List items {self.id}'


class UsersLists(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='id', blank=True)
    user = models.ForeignKey(
        CustomUser,on_delete=models.CASCADE)
    list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Users List'
        verbose_name_plural = 'Users Lists'

    def __str__(self) -> str:
        return f'UserLists for user {self.user.email}'

todo/forms.py
from django import forms
from todo.models import TodoList


class CreateForm(forms.Form):
    title = forms.CharField(max_length=100, label='Название',
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(max_length=255, label='Описание',
        widget=forms.TextInput(attrs={'class': 'form-control'}))

todo/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from todo.forms import CreateForm
from todo.models import *


@login_required
def list_view(request):

    user_list = (request.user).userslists_set.all()
    res = []
    for obj in user_list:
        todo_list = obj.list
        list_item = ListItems.objects.select_related(
            'list').filter(list__id=todo_list.id)
        items = []
        for item in list_item:
            items.append(item.item)

        res.append({'todo_list': todo_list, 'items': items})

    return render(request, 'list.html', {'obj': res})


def add_item(request, id):
    form = CreateForm(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        title = data.get('title')
        description = data.get('description')
        item = TodoItem(title=title, description=description, done=False)
        item.save()
        li = ListItems(list=TodoList.objects.get(id=id),
                       item=TodoItem.objects.latest('id'))
        li.save()
        return redirect('todo:list')
    return render(request, 'add_item.html', {'form': form})


def add_list(request):
    form = CreateForm(request.POST or None)
    user = request.user
    if form.is_valid():
        data = form.cleaned_data
        title = data.get('title')
        description = data.get('description')
        todo_lst = TodoList(title=title, description=description)
        todo_lst.save()
        user_lst = UsersLists(user=user, list=TodoList.objects.latest('id'))
        user_lst.save()
        return redirect('todo:list')
    return render(request, 'add_item.html', {'form': form})


def delete_task(request, id):
    item = get_object_or_404(TodoItem, id=id)
    context = {'obj': item}
    if request.method == 'GET':
        return render(request, 'delete_task.html', context)
    elif request.method == 'POST':
        item.delete()
        messages.success(request,  'The item has been deleted successfully.')
        return redirect('todo:list')
    

def done_task(request, id):
    item = TodoItem.objects.get(id=id)
    item.done = True
    item.save()
    return redirect('todo:list')


def hide_done(request):
    pass


def home_view(request):
    return render(request, 'base.html')

todo/templates/add_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form method="POST" action="">{% csrf_token %}
                <div class="form-group">
                    {{ form.as_p }}
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}

todo/templates/base.html
{% url 'todo:list' as list %}
{% url 'users:logout' as logout %}
{% url 'users:login' as login %}
{% url 'users:register' as register %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <style>
      body {
        margin-left: 15%;
        margin-right: 15%;
        background-image: linear-gradient(
          to bottom,
          rgba(255, 255, 0, 0.5),
          rgba(0, 0, 255, 0.5)
        );
      }

      h1 {
        text-align: center;
      }

      nav {
        border: 2px solid white;
        border-radius: 20px;
        background-image: red;
      }

      .logout {
        float: right;
      }
    </style>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ToDolist</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-link {% if request.path == list %} active {% endif %}" aria-current="page" href={% url 'todo:list' %}>My ToDo</a>
                <a class="nav-link " aria-current="page" href={% url 'users:logout' %}>logout</a>
              {% else %}
                <a class="nav-link " href={% url 'users:login' %}>Login</a>
                <a class="nav-link " href={% url 'users:register' %}>Register</a>
              {% endif %}
              {% comment %} <a class="nav-link disabled">Disabled</a> {% endcomment %}
            </div>
          </div>
        </div>
      </nav>

      <h1>WELCOME TO YOUR TODOLIST APP!</h1>

      {% block content %}
      {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/delete_task.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure that you want to delete the ToDo "{{obj.title}}"?</p>
        <div>
            <button type="submit">Yes, Delete</button>
            <a href={% url 'todo:list' %}>Cancel</a>
        </div>
    </form>
{% endblock content %}

todo/templates/list.html
{% extends 'base.html'%}

{% block content %}

<style>

    .list {
        border: 3px solid black;
        border-radius: 50px;
        margin: 0px 15px 15px;
        padding-left: 15px;
        background-color: gray;
        font-family: Verdana;
    }

    .bord {
        border: 2px solid red;
        border-radius: 25px;
        margin: 0px 15px 15px;
        padding-left: 15px;
        background-color: gray;
        opacity: 0.5;
        font-family: Verdana;
    }

    .bord p{
        font-size: 30px;
    }

  </style>

    {% for o in obj %}
    <div class='list'>
        <h1>{{o.todo_list.title}}</h1>
        <h2>{{o.todo_list.description}}</h2>

        {% for item in o.items %}
            <div class='bord'>
                <h1>{{item.title}}</h1>
                <p>{{item.description}}</p>
                {% if item.done %}
                    <p>Выполнено</p>
                {% else %}
                    <p>Не Выполнено</p>
                {% endif %}
                {% comment %} <input type="checkbox"> {% endcomment %}
                <p>
                    <a href={% url 'todo:done' item.id %}>Сделано!</a>
                    <a href={% url 'todo:delete' item.id %}>Delete</a> 
                </p>
            </div>
        {% endfor %}
        <p>
            <a href={% url 'todo:add-item' o.todo_list.id%}>Add ToDo Item</a> 
        </p>
    </div>
    {% endfor %}
    <p>
        <a href={% url 'todo:add-list'%}>Add ToDo List</a> 
    </p>
{% endblock %}

{% comment %} <!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8" />
  <title>HTML5</title>
  <style>

    .list {
        border: 3px solid black;
        border-radius: 50px;
        margin: 0px 15px 15px;
        padding-left: 15px;
        background-color: gray;
        font-family: Verdana;
    }

    .bord {
        border: 2px solid red;
        border-radius: 25px;
        margin: 0px 15px 15px;
        padding-left: 15px;
        background-color: gray;
        opacity: 0.5;
        font-family: Verdana;
    }

    .bord p{
        font-size: 30px;
    }

  </style>
 </head>
 <body>

    {% for o in obj %}
        <div class='list'>
            <h1>{{o.todo_list.title}}</h1>
            <h2>{{o.todo_list.description}}</h2>

            {% for item in o.items %}
                <div class='bord'>
                    <h1>{{item.title}}</h1>
                    <p>{{item.description}}</p>
                    <p>{{item.done}}</p>
                    <input type="checkbox">
                </div>
            {% endfor %}
        </div>
    {% endfor %}

 </body>
</html> {% endcomment %}